AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'

Description: multi-stack-poc

Parameters:
  BuildId:
    Type: String
    Default: "MISSINGBUILDID"

Resources:
  GetCertificates:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Lambda for getting a list of all existing certificates
      FunctionName: !Sub "multi-stack-poc-GetCertificates"
      Handler: "com.wirelesscar.vw.tscs.functions.GetCertificates::handleRequest"
      CodeUri: !Sub "s3://wirelesscar-multi-stack-poc-serverless-deployment-bucket/multi-stack-poc-shaded-${BuildId}-SNAPSHOT.jar"
      Role: !GetAtt GetCertificatesRole.Arn
      Runtime: java8
      Tracing: Active
      MemorySize: 512
      Timeout: 10

  GetCertificatesRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 'multi-stack-poc-GetCertificatesRole'
      AssumeRolePolicyDocument:
        Statement:
          Action: 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - Fn::ImportValue: !Sub "multi-stack-poc-ReadCertificatesTablePolicy"
