AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'

Description: multi-stack-poc

Parameters:
  BuildId:
    Type: String
    Default: "MISSINGBUILDID"

Resources:
  GetCertificates:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Lambda for getting a list of all existing certificates
      FunctionName: !Sub "multi-stack-poc-GetCertificates"
      Handler: "com.wirelesscar.vw.tscs.functions.GetCertificates::handleRequest"
      CodeUri:
        Bucket: wirelesscar-multi-stack-poc-serverless-deployment-bucket
        Key: !Sub multi-stack-poc-shaded-${BuildId}-SNAPSHOT.jar
      Role: !GetAtt GetCertificatesRole.Arn
      Runtime: java8
      Tracing: Active
      MemorySize: 512
      Timeout: 10

  GetCertificatesRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 'multi-stack-poc-GetCertificatesRole'
      AssumeRolePolicyDocument:
        Statement:
          Action: 'sts:AssumeRole'
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - Fn::ImportValue: !Sub "multi-stack-poc-ReadCertificatesTablePolicy"
      Policies:
        - PolicyName: !Sub "multi-stack-poc-GetCertificatesRole-policy"
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 'sts:AssumeRole'
                Resource: !Ref ConfigRole


  # API
  TrustStoreContainerServiceAPI:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: !Sub "multi-stack-poc"
      Parameters:
        endpointConfigurationTypes: REGIONAL
      EndpointConfiguration:
        Types:
          - REGIONAL
      Body:
        openapi: 3.0.0
        info:
          title: !Sub "multi-stack-poc-Trust Store Container Service API"
        paths:

          /certificates:
            get:
              summary: Endpoint to get a list of all certificates
              operationId: "getCertificates"
              consumes:
                - application/json
              headers:
                - Content-Type: "application/json"
              x-amazon-apigateway-integration:
                uri: !Sub 'arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetCertificates.Arn}/invocations'
                httpMethod: "POST"
                type: aws_proxy