name: Deploy CloudFormation Stack
on: 
  push:
    branches:
    - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo We are starting the deploy!
        echo test, and deploy your project.
        
    - name: AWS cli install action
      uses: chrislennon/action-aws-cli@1.1
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id:  ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: eu-west-1

        
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x)
        java-version: 1.8
        
    - name: Build java files
      run: |
        cd service
        mvn package
        
    - name: Upload to S3 Bucket
      run: |
        cd service/target
        aws s3 cp multi-stack-poc-shaded-0-SNAPSHOT.jar s3://wirelesscar-multi-stack-poc-serverless-deployment-bucket/
        
    - name: Cloudformation Deploy
      run: |
        cd service
        aws cloudformation package --template-file template.yml --output-template-file serverless-output.yaml --s3-bucket wirelesscar-multi-stack-poc-serverless-deployment-bucket
        aws cloudformation deploy --template-file serverless-output.yaml --stack-name multi-stack-poc --s3-bucket wirelesscar-multi-stack-poc-serverless-deployment-bucket
 
#     - name: CloudFormation Deploy Old
#       uses: mgenteluci/cloudformation-deploy-action@v1.3.0
#       env:
#         TEMPLATE: 'service/template.yml'
#         AWS_STACK_NAME: 'multi-stack-poc'
#         AWS_REGION: 'eu-west-1'
#         AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
#         AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
#         AWS_DEPLOY_BUCKET: ${{secrets.AWS_DEPLOY_BUCKET}}
