name: Deploy CloudFormation Stack
on: 
  push:
    branches:
    - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo We are starting the deploy!
        echo test, and deploy your project.

 
    - name: CloudFormation Deploy
      uses: mgenteluci/cloudformation-deploy-action@v1.3.0
      env:
        TEMPLATE: 'service/template.yml'
        AWS_STACK_NAME: 'multi-stack-poc'
        AWS_REGION: 'eu-west-1'
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_DEPLOY_BUCKET: ${{secrets.AWS_DEPLOY_BUCKET}}
