name: Deploy CloudFormation Stack
on: 
  push:
    branches:
    - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: AWS cli install action
      uses: chrislennon/action-aws-cli@1.1
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id:  ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: eu-west-1

    - name: Cloudformation Database Deploy
      run: |
        cd database
        aws cloudformation package --template-file template.yml --output-template-file database-output.yaml --s3-bucket wirelesscar-multi-stack-poc-serverless-deployment-bucket
        aws cloudformation deploy --template-file database-output.yaml --stack-name multi-stack-poc-db --s3-bucket wirelesscar-multi-stack-poc-serverless-deployment-bucket --capabilities CAPABILITY_NAMED_IAM  --no-fail-on-empty-changeset

    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        # The Java version to make available on the path. Takes a whole or semver Java version, or 1.x syntax (e.g. 1.8 => Java 8.x)
        java-version: 1.8
        
    - name: Build java files
      run: |
        cd service
        mvn package
        
    - name: Upload to S3 Bucket
      run: |
        cd service/target
        aws s3 cp multi-stack-poc-shaded-0-SNAPSHOT.jar s3://wirelesscar-multi-stack-poc-serverless-deployment-bucket/
        
    - name: Cloudformation Deploy
      run: |
        cd service
        aws cloudformation package --template-file template.yml --output-template-file serverless-output.yaml --s3-bucket wirelesscar-multi-stack-poc-serverless-deployment-bucket
        aws cloudformation deploy --template-file serverless-output.yaml --stack-name multi-stack-poc-service --s3-bucket wirelesscar-multi-stack-poc-serverless-deployment-bucket --capabilities CAPABILITY_NAMED_IAM  --no-fail-on-empty-changeset
 
